package de.kherud.llama.foreign;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class llama_token_data_array extends Structure {
	public de.kherud.llama.foreign.llama_token_data.ByReference data;
	public de.kherud.llama.foreign.llama_token_data.ByReference getData() {
		return data;
	}
	public void setData(de.kherud.llama.foreign.llama_token_data.ByReference data) {
		this.data = data;
	}
	public NativeSize size;
	public NativeSize getSize() {
		return size;
	}
	public void setSize(NativeSize size) {
		this.size = size;
	}
	public byte sorted;
	public byte getSorted() {
		return sorted;
	}
	public void setSorted(byte sorted) {
		this.sorted = sorted;
	}
	public llama_token_data_array() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("data", "size", "sorted");
	}
	public llama_token_data_array(de.kherud.llama.foreign.llama_token_data.ByReference data, NativeSize size, byte sorted) {
		super();
		this.data = data;
		this.size = size;
		this.sorted = sorted;
	}
	public llama_token_data_array(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends llama_token_data_array implements Structure.ByReference {
		
	};
	public static class ByValue extends llama_token_data_array implements Structure.ByValue {
		
	};
}
