package de.kherud.llama.foreign;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class llama_timings extends Structure {
	public double t_start_ms;
	public double getT_start_ms() {
		return t_start_ms;
	}
	public void setT_start_ms(double t_start_ms) {
		this.t_start_ms = t_start_ms;
	}
	public double t_end_ms;
	public double getT_end_ms() {
		return t_end_ms;
	}
	public void setT_end_ms(double t_end_ms) {
		this.t_end_ms = t_end_ms;
	}
	public double t_load_ms;
	public double getT_load_ms() {
		return t_load_ms;
	}
	public void setT_load_ms(double t_load_ms) {
		this.t_load_ms = t_load_ms;
	}
	public double t_sample_ms;
	public double getT_sample_ms() {
		return t_sample_ms;
	}
	public void setT_sample_ms(double t_sample_ms) {
		this.t_sample_ms = t_sample_ms;
	}
	public double t_p_eval_ms;
	public double getT_p_eval_ms() {
		return t_p_eval_ms;
	}
	public void setT_p_eval_ms(double t_p_eval_ms) {
		this.t_p_eval_ms = t_p_eval_ms;
	}
	public double t_eval_ms;
	public double getT_eval_ms() {
		return t_eval_ms;
	}
	public void setT_eval_ms(double t_eval_ms) {
		this.t_eval_ms = t_eval_ms;
	}
	public int n_sample;
	public int getN_sample() {
		return n_sample;
	}
	public void setN_sample(int n_sample) {
		this.n_sample = n_sample;
	}
	public int n_p_eval;
	public int getN_p_eval() {
		return n_p_eval;
	}
	public void setN_p_eval(int n_p_eval) {
		this.n_p_eval = n_p_eval;
	}
	public int n_eval;
	public int getN_eval() {
		return n_eval;
	}
	public void setN_eval(int n_eval) {
		this.n_eval = n_eval;
	}
	public llama_timings() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("t_start_ms", "t_end_ms", "t_load_ms", "t_sample_ms", "t_p_eval_ms", "t_eval_ms", "n_sample", "n_p_eval", "n_eval");
	}
	public llama_timings(double t_start_ms, double t_end_ms, double t_load_ms, double t_sample_ms, double t_p_eval_ms, double t_eval_ms, int n_sample, int n_p_eval, int n_eval) {
		super();
		this.t_start_ms = t_start_ms;
		this.t_end_ms = t_end_ms;
		this.t_load_ms = t_load_ms;
		this.t_sample_ms = t_sample_ms;
		this.t_p_eval_ms = t_p_eval_ms;
		this.t_eval_ms = t_eval_ms;
		this.n_sample = n_sample;
		this.n_p_eval = n_p_eval;
		this.n_eval = n_eval;
	}
	public llama_timings(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends llama_timings implements Structure.ByReference {
		
	};
	public static class ByValue extends llama_timings implements Structure.ByValue {
		
	};
}
